
spring:
  datasource:
    name: szdata #数据库名称
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/sheji?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
server:
  port: 1478
  max-http-header-size: 1024000
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.sz.limitHeight.model
logging:
  level:
    com:
      neo:
        mapper: debug
